import type { Student } from "./student-types";

export const initialStudents: Student[] = [
  {
    id: "student-1",
    firstName: "Ульяна",
    lastName: "Шмагина",
    phone: "+7 916 345-18-02",
    email: "ulyana@example.ru",
    lessonPrice: 1400,
    lessonDuration: 90,
    notes: "Готовится к ОГЭ. Уделить внимание квадратным уравнениям и задачам второй части.",
    balance: 2800,
    status: "active",
    upcomingLessons: [
      { id: "ul-1", date: "17 августа", time: "09:00–10:30", subject: "Математика" },
      { id: "ul-2", date: "19 августа", time: "16:00–17:30", subject: "Математика" },
    ],
    parents: [],
  },
  {
    id: "student-2",
    firstName: "Павел",
    lastName: "Новиков",
    phone: "+7 903 118-24-40",
    email: "pavel.novikov@example.ru",
    lessonPrice: 1600,
    lessonDuration: 90,
    notes: "Физика, 10 класс. Любит практические задачи, теорию лучше закреплять короткими конспектами.",
    balance: 1600,
    status: "active",
    upcomingLessons: [{ id: "pn-1", date: "15 августа", time: "10:00–11:30", subject: "Физика" }],
    parents: [],
  },
  {
    id: "student-3",
    firstName: "Мария",
    lastName: "Крюкова",
    phone: "+7 925 672-50-19",
    email: "maria.k@example.ru",
    lessonPrice: 1400,
    lessonDuration: 90,
    notes: "Повторяем геометрию за 8 класс. Хороший темп, домашние работы сдаёт вовремя.",
    balance: 4200,
    status: "active",
    upcomingLessons: [{ id: "mk-1", date: "21 августа", time: "11:00–12:30", subject: "Геометрия" }],
    parents: [],
  },
  {
    id: "student-4",
    firstName: "Катя",
    lastName: "Игнатова",
    phone: "+7 916 912-33-07",
    email: "katya.i@example.ru",
    lessonPrice: 1400,
    lessonDuration: 60,
    notes: "Алгебра, 9 класс. Занятия онлайн.",
    balance: 0,
    status: "active",
    upcomingLessons: [{ id: "ki-1", date: "18 августа", time: "17:00–18:00", subject: "Алгебра" }],
    parents: [],
  },
  {
    id: "student-5",
    firstName: "Алексей",
    lastName: "Миронов",
    phone: "+7 985 440-78-22",
    email: "alex.mironov@example.ru",
    lessonPrice: 1200,
    lessonDuration: 60,
    notes: "Занятия завершены в мае.",
    balance: 0,
    status: "archived",
    upcomingLessons: [],
    parents: [],
  },
];

export const emptyStudentDraft = {
  firstName: "",
  lastName: "",
  phone: "",
  email: "",
  dateOfBirth: "",
  address: "",
  parentFirstName: null,
  parentLastName: null,
  parentPhone: null,
  parentEmail: null,
  lessonPrice: 1400,
  lessonDuration: 60,
  notes: "",
};
